version: '3.8'

services:
  # PHP service
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php
    volumes:
      - ./laravel:/var/www/html
    networks:
      - my_network
    ports:
      - "9000:9000"

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./laravel:/var/www/html
    networks:
      - my_network
    ports:
      - "80:80"

  # MySQL service
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network
    ports:
      - "3306:3306"

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
