version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php1:
    build:
      context: ./php1
    container_name: php1
    volumes:
      - ./app:/var/www/html
      - ./app/.env.php1:/var/www/html/.env
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    depends_on:
      - db

  php2:
    build:
      context: ./php2
    container_name: php2
    volumes:
      - ./app:/var/www/html
      - ./app/.env.php2:/var/www/html/.env
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    depends_on:
      - db

  nginx1:
    build:
      context: ./nginx1
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php1

  nginx2:
    build:
      context: ./nginx2
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php2

volumes:
  db_data:
